name: Fetch System Configuration

on:
  push:
    
jobs:
  build:
    name: Check Out Repo
    runs-on: ubuntu-latest
    steps:
    - name: Check-Out-Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: main

    - name: Build Database
      continue-on-error: true
      run: |
        cd main
        python3 -m venv .venv
        source ./.venv/bin/activate
        pip install -r requirements.txt
        python3 build_database.py

    - name: Push to Server
      run: |
        cd main
        apt update -y
        apt install sshpass -y
        sshpass -p "$MINI_PW" scp -o StrictHostKeyChecking=no ./tils.db jacob@mini.tailb54fb2.ts.net:/home/jacob/containers_enabled/Today_I_Learned/src/
      env:
        MINI_PW: ${{ secrets.MINI_PW }}

    - name: Update README
      run: |
        cd main
        source ./.venv/bin/activate
        python3 update_readme.py > README.md
        git config user.email "jacob.stephen.nellis@gmail.com"
        git config user.name "README-Updater-BOT"
        git add README.md
        git commit -m 'AUTOMATED: Update README'
        git push