name: Fetch System Configuration

on:
  push:
    
jobs:
  build:
    name: build
    runs-on: ubuntu
    steps:
    - name: Check-Out-Repo
      uses: actions/checkout@v4

    - name: Setup Machine
      continue-on-error: true
      run: |
        su - jacob
        ls
        pwd
        cd Today-I-Learned
        python3 -m venv .venv
        source ./.venv/bin/activate
        pip install -r requirements.txt
        python3 build_database.py
        scp -i /home/jacob/.ssh/master.pem -o StrictHostKeyChecking=no ./tils.db ubuntu@3.146.120.38:/home/ubuntu/Today_I_Learned/src/