name: Fetch System Configuration

on:
  push:
    
jobs:
  build:
    name: Check Out Repo
    runs-on: ubuntu-latest
    steps:
    - name: Check-Out-Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: main

    - name: Build Database
      run: |
        cd main
        python3 -m venv .venv
        source ./.venv/bin/activate
        pip install -r requirements.txt
        python3 build_database.py

    - name: Build and Push Docker Image
      env:
        REGISTRY: ${{ secrets.REGISTRY }}
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      run: |
        cd main
        if [ ! -f "tils.db" ]; then
          echo "tils.db not found; did the DB step succeed?" >&2
          exit 1
        fi
        if [ -z "$REGISTRY" ] || [ -z "$REGISTRY_USERNAME" ] || [ -z "$REGISTRY_PASSWORD" ] || [ -z "$IMAGE_NAME" ]; then
          echo "Registry settings missing. Define REGISTRY, REGISTRY_USERNAME, REGISTRY_PASSWORD, IMAGE_NAME secrets." >&2
          exit 1
        fi
        echo "Logging into container registry $REGISTRY"
        echo "$REGISTRY_PASSWORD" | docker login "$REGISTRY" -u "$REGISTRY_USERNAME" --password-stdin
        # Ensure the image tag includes the registry prefix
        if echo "$IMAGE_NAME" | grep -qE '^[^/]+\.[^/]+/'; then
          FULL_IMAGE="$IMAGE_NAME"
        else
          FULL_IMAGE="$REGISTRY/$IMAGE_NAME"
        fi
        echo "Building image: $FULL_IMAGE"
        docker build -t "$FULL_IMAGE" .
        docker push "$FULL_IMAGE"

    - name: Update README
      run: |
        cd main
        source ./.venv/bin/activate
        python3 update_readme.py > README.md
        git config user.email "jacob.stephen.nellis@gmail.com"
        git config user.name "README-Updater-BOT"
        git add README.md
        git commit -m 'AUTOMATED: Update README'
        git push
